steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'

- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: |
      print('This is try pipeline')

- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: '$(System.DefaultWorkingDirectory)'