steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'

- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: |
      print('This is try pipeline')


# Python script
# Run a Python file or inline script
- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: '$(System.DefaultWorkingDirectory)'
    script: python src/Test1.py